Portofolio desktop version: Resposive Web Design
Marcraphael12/Marc-Raphael-Portofolio pull request #6
Opened 2021-06-16 23:10 UTC by Marcraphael12

check with the others if the media queries have been used correctly to switch from the mobile version to the desktop version!
I worked hard to make this, but maybe my work is not enough to deploy this project. So I would be happy to see your reviews and add the better solution you will propose!

2021-06-17 02:03 UTC, vichuge requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi @Marcraphael12, 

Good job so far!
Excellente project!!! I could see the hours working on this and check all in detail, I saw you with a great future as a front-end developer, you have it.

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 
- No Linters error ✔️ 
- Your mobile design is... I ❤️ it, I'd pay for this, really! ✔️ 
- Seriously, your mobile design is perfect ✔️ 

## Aspects to improve ♻️

- [ ] The mobile design is perfect, but according to this project, you need to have tablet and desktop size too. I recommend you to check the figma template to know how should look on desktop and tablet, becasue at this point, the 3 are the same.
- This is the problem in desktop, when you see it, is the same as mobile but, it should be different
![image](https://user-images.githubusercontent.com/20563252/122318905-758dec00-cee5-11eb-9a00-91f206e15e82.png)

- [ ] Something that could help for this is use media queries for the Desktop breakpoint in the CSS file.(min-width > 992px - 1100px)

```html
// Passes the requirement (propper size)
@media screen and (max-width: 1080px) {
/*
.
.

*/
}
```

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-17 08:05 UTC, Marcraphael12 commented
> # Required Changes   
> Hi @Marcraphael12,
> 
> Good job so far!
> Excellente project!!! I could see the hours working on this and check all in detail, I saw you with a great future as a front-end developer, you have it.
> 
> ![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)
> 
> ## Good points 
> * No Linters error heavy_check_mark
> * Your mobile design is... I heart it, I'd pay for this, really! heavy_check_mark
> * Seriously, your mobile design is perfect heavy_check_mark
> 
> ## Aspects to improve 
> * [ ]  The mobile design is perfect, but according to this project, you need to have tablet and desktop size too. I recommend you to check the figma template to know how should look on desktop and tablet, becasue at this point, the 3 are the same.
> * This is the problem in desktop, when you see it, is the same as mobile but, it should be different
>   ![image](https://user-images.githubusercontent.com/20563252/122318905-758dec00-cee5-11eb-9a00-91f206e15e82.png)
> * [x]  Something that could help for this is use media queries for the Desktop breakpoint in the CSS file.(min-width > 992px - 1100px)
> 
> ```
> // Passes the requirement (propper size)
> @media screen and (max-width: 1080px) {
> /*
> .
> .
> 
> */
> }
> ```
> 
> Cheers and Happy coding!
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Thank you a lot for this comment! I can see you opened the deployment link in the README file. But this deployment just hosts the mobile version of my project, for now, the desktop version has not yet been merged. To provide you a view of the last result of this work, please take a look at these pictures below!

![Capture d’écran de 2021-06-17 08-54-07](https://user-images.githubusercontent.com/68046127/122356412-afdda480-cf4a-11eb-9fbd-b7e7607cce2f.png)
![Capture d’écran de 2021-06-17 08-54-43](https://user-images.githubusercontent.com/68046127/122356496-c4ba3800-cf4a-11eb-8912-def273b11f9c.png)
![Capture d’écran de 2021-06-17 08-54-48](https://user-images.githubusercontent.com/68046127/122356519-cab01900-cf4a-11eb-8f95-0af6b75815e1.png)
![Capture d’écran de 2021-06-17 08-54-54](https://user-images.githubusercontent.com/68046127/122356573-d4d21780-cf4a-11eb-9354-69e8308eb95e.png)
![Capture d’écran de 2021-06-17 08-55-14](https://user-images.githubusercontent.com/68046127/122356611-dbf92580-cf4a-11eb-940c-a7406d3d33aa.png)
![Capture d’écran de 2021-06-17 08-55-18](https://user-images.githubusercontent.com/68046127/122356662-e9aeab00-cf4a-11eb-9f6f-c80cef9b4c24.png)
![Capture d’écran de 2021-06-17 08-55-23](https://user-images.githubusercontent.com/68046127/122356796-0c40c400-cf4b-11eb-9dc9-3b4571d40f65.png)

2021-06-17 08:12 UTC, Marcraphael12 commented
> > # Required Changes
> > Hi @Marcraphael12,
> > Good job so far!
> > Excellente project!!! I could see the hours working on this and check all in detail, I saw you with a great future as a front-end developer, you have it.
> > ![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)
> > ## Good points
> > 
> > * No Linters error heavy_check_mark
> > * Your mobile design is... I heart it, I'd pay for this, really! heavy_check_mark
> > * Seriously, your mobile design is perfect heavy_check_mark
> > 
> > ## Aspects to improve
> > 
> > * [ ]   The mobile design is perfect, but according to this project, you need to have tablet and desktop size too. I recommend you to check the figma template to know how should look on desktop and tablet, becasue at this point, the 3 are the same.
> > * This is the problem in desktop, when you see it, is the same as mobile but, it should be different
> >   ![image](https://user-images.githubusercontent.com/20563252/122318905-758dec00-cee5-11eb-9a00-91f206e15e82.png)
> > * [x]   Something that could help for this is use media queries for the Desktop breakpoint in the CSS file.(min-width > 992px - 1100px)
> > 
> > ```
> > // Passes the requirement (propper size)
> > @media screen and (max-width: 1080px) {
> > /*
> > .
> > .
> > 
> > */
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Cheers and Happy coding!
> > Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> > **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> > _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
> 
> Thank you a lot for this comment! I can see you opened the deployment link in the README file. But this deployment just hosts the mobile version of my project, for now, the desktop version has not yet been merged. To provide you a view of the last result of this work, please take a look at these pictures below!
> 
> ![Capture d’écran de 2021-06-17 08-54-07](https://user-images.githubusercontent.com/68046127/122356412-afdda480-cf4a-11eb-9fbd-b7e7607cce2f.png)
> ![Capture d’écran de 2021-06-17 08-54-43](https://user-images.githubusercontent.com/68046127/122356496-c4ba3800-cf4a-11eb-8912-def273b11f9c.png)
> ![Capture d’écran de 2021-06-17 08-54-48](https://user-images.githubusercontent.com/68046127/122356519-cab01900-cf4a-11eb-8f95-0af6b75815e1.png)
> ![Capture d’écran de 2021-06-17 08-54-54](https://user-images.githubusercontent.com/68046127/122356573-d4d21780-cf4a-11eb-9354-69e8308eb95e.png)
> ![Capture d’écran de 2021-06-17 08-55-14](https://user-images.githubusercontent.com/68046127/122356611-dbf92580-cf4a-11eb-940c-a7406d3d33aa.png)
> ![Capture d’écran de 2021-06-17 08-55-18](https://user-images.githubusercontent.com/68046127/122356662-e9aeab00-cf4a-11eb-9f6f-c80cef9b4c24.png)
> ![Capture d’écran de 2021-06-17 08-55-23](https://user-images.githubusercontent.com/68046127/122356796-0c40c400-cf4b-11eb-9dc9-3b4571d40f65.png)
![Capture d’écran de 2021-06-17 09-06-34](https://user-images.githubusercontent.com/68046127/122357914-0eefe900-cf4c-11eb-80fd-47ef3bb17d8c.png)
I hope this is more descriptive!

2021-06-17 10:33 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

**Thank you for stating the last reviewer's point of confusion.  Your PR  looks professional with a nice title and summary, including commit messages :+1:
Your project looks great so far 👏**

__However, you need to make some required changes before moving on to the next assignment.__
> Keep in mind that your long hours of work are appreciated. However, the code review process is for improving the code you wrote, and not for criticizing it :blush: 

### **Required Changes :recycle:**
Kindly check my inline comments below :bowing_man: 

### **Optional Changes** :zap: 
N/A

* * *
**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review unless it is requested otherwise.**

*Feel free to leave any questions or comments in the PR thread if something is not 100% clear.*

*REMINDER: As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can [request a second opinion using this form](https://airtable.com/shrQAqnBwek5a0O0s).*

_**Please make the required changes and submit another review request when you are done.**_

* * *

Re-reviewed by: [**Taofeek Olalere**](https://github.com/teekaytech)
*Cheers and Happy Coding* :smiley:

2021-06-17 10:33 UTC, teekaytech commented on index.html
> +          <li class="class-sections-titles works-section-title">Projects</li>
In the `Projects` section, kindly observe the following:

- [ ] The `Projects` text should read from top to bottom as observed in the Figma design.
- [ ] Next to the title taking 70% of the page's width, with no margin on the right, and aligned to the right there's a featured project.

_**Figma Design**_
![figma](https://user-images.githubusercontent.com/26856491/122377821-5468e200-cf5d-11eb-9324-bb2b5185f385.png)

_**Your Design**_
![design](https://user-images.githubusercontent.com/26856491/122377366-ede3c400-cf5c-11eb-83a3-2109263731a8.png)

_For other Regular (non-featured) projects_

- [ ] The first one is just a mockup image aligned to the left of the page with no margin on the page and it takes about 25% of the page's width.

- [ ] The second project shares the first one's row but is bigger in height (taking also part of the next row also) and looks just like the featured project but the description is above the picture; also takes about 25% of the page's width and is aligned completely to the right with no margin in the page.

- [ ] The third project is just a mockup image (like the first one) and is below the first project with no margin on top or left, this one takes 50% of the page's width.

- [ ] Lastly, there's a fourth project below the third one but starts in the center of the page and it takes about 30% of the page's width.

2021-06-17 10:33 UTC, teekaytech commented on index.html
> +        <div class="about-container">
- [ ] Something seems to be wrong with the bullets of the list items listed in the `Languages`, `Skills`, and the `Frameworks` section: they seem to be overlapping on the text. I think you should have a look and fix it.
- [ ] You might want to consider increasing the margins to the left and right of all the components on your page. The components look so close to the left and right margins of the container compared to the Figma tempate at the moment.

**_Figma Template_**
![figma](https://user-images.githubusercontent.com/26856491/122379449-c7268d00-cf5e-11eb-93e4-298f167142b5.png)

**_Your Design_**
![design](https://user-images.githubusercontent.com/26856491/122379459-caba1400-cf5e-11eb-9433-64df19a3f904.png)

2021-06-18 04:46 UTC, vichuge approved these changes
# Approved project! ✅ 🥳 🎈 🎉🎉🎉🎉🎉🎉🎉🎉 

Hi @Marcraphael12, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![InbornCandidHornet-size_restricted](https://user-images.githubusercontent.com/20563252/121368858-ff93ee80-c900-11eb-9ee8-e43b2b0d3382.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-18 07:57 UTC, merged